# 本地开发时使用根路径，生产环境通过 GitHub Actions 覆盖为 /blog/
baseURL = '/'
languageCode = 'zh-cn'
title = '我的技术博客'
theme = 'PaperMod'
hasCJKLanguage = true
copyright = "QiuQiu"

[outputs]
home = ["HTML", "RSS", "JSON"]


[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  UseHugoToc = true
  author = "QiuQiu"

  [params.assets]
    favicon = "/favicon.png"
    favicon16x16 = "/favicon.png"
    favicon32x32 = "/favicon.png"
    apple_touch_icon = "/favicon.png"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 20
